server:
  port: 9987

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flaskexample?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/hyanghae
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # MySQLDialect H2Dialect


logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    token:
      secret-key: "remoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoaremoa"
      expiration-minutes: 1    # 3시간 -> 30분
      refresh-expiration-hours: 24    # 리프레시 토큰 유효시간은 24시간


flask:
  base-url: http://localhost:5000/ml/api/  # 로컬 프로파일용 Flask URL
