server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flaskexample?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/hyanghae
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug