server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://remoa-db.c7smw8oye3a4.ap-northeast-2.rds.amazonaws.com:3306/hyanghae?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug