insert into place_register(member_id, place_id, created_time) values(1, 217, now());
insert into place_register(member_id, place_id, created_time) values(1, 70, now());
insert into place_register(member_id, place_id, created_time) values(1, 674, now());
insert into place_register(member_id, place_id, created_time) values(1, 148, now());
insert into place_register(member_id, place_id, created_time) values(1, 632, now());
insert into place_register(member_id, place_id, created_time) values(1, 378, now());
insert into place_register(member_id, place_id, created_time) values(1, 472, now());
insert into place_register(member_id, place_id, created_time) values(1, 251, now());
insert into place_register(member_id, place_id, created_time) values(1, 552, now());
insert into place_register(member_id, place_id, created_time) values(1, 268, now());
insert into place_register(member_id, place_id, created_time) values(2, 653, now());
insert into place_register(member_id, place_id, created_time) values(2, 586, now());
insert into place_register(member_id, place_id, created_time) values(2, 75, now());
insert into place_register(member_id, place_id, created_time) values(2, 535, now());
insert into place_register(member_id, place_id, created_time) values(2, 380, now());
insert into place_register(member_id, place_id, created_time) values(2, 139, now());
insert into place_register(member_id, place_id, created_time) values(2, 151, now());
insert into place_register(member_id, place_id, created_time) values(2, 670, now());
insert into place_register(member_id, place_id, created_time) values(2, 699, now());
insert into place_register(member_id, place_id, created_time) values(2, 170, now());
insert into place_register(member_id, place_id, created_time) values(3, 371, now());
insert into place_register(member_id, place_id, created_time) values(3, 577, now());
insert into place_register(member_id, place_id, created_time) values(3, 401, now());
insert into place_register(member_id, place_id, created_time) values(3, 442, now());
insert into place_register(member_id, place_id, created_time) values(3, 311, now());
insert into place_register(member_id, place_id, created_time) values(3, 349, now());
insert into place_register(member_id, place_id, created_time) values(3, 216, now());
insert into place_register(member_id, place_id, created_time) values(3, 510, now());
insert into place_register(member_id, place_id, created_time) values(3, 343, now());
insert into place_register(member_id, place_id, created_time) values(3, 211, now());

insert into place_like(member_id, place_id) values(1, 730);
insert into place_like(member_id, place_id) values(1, 336);
insert into place_like(member_id, place_id) values(1, 47);
insert into place_like(member_id, place_id) values(1, 572);
insert into place_like(member_id, place_id) values(1, 325);
insert into place_like(member_id, place_id) values(1, 37);
insert into place_like(member_id, place_id) values(1, 519);
insert into place_like(member_id, place_id) values(1, 295);
insert into place_like(member_id, place_id) values(1, 333);
insert into place_like(member_id, place_id) values(1, 631);
insert into place_like(member_id, place_id) values(1, 369);
insert into place_like(member_id, place_id) values(1, 366);
insert into place_like(member_id, place_id) values(1, 75);
insert into place_like(member_id, place_id) values(1, 199);
insert into place_like(member_id, place_id) values(1, 237);
insert into place_like(member_id, place_id) values(1, 600);
insert into place_like(member_id, place_id) values(1, 203);
insert into place_like(member_id, place_id) values(1, 85);
insert into place_like(member_id, place_id) values(1, 720);
insert into place_like(member_id, place_id) values(1, 624);
insert into place_like(member_id, place_id) values(2, 579);
insert into place_like(member_id, place_id) values(2, 510);
insert into place_like(member_id, place_id) values(2, 430);
insert into place_like(member_id, place_id) values(2, 363);
insert into place_like(member_id, place_id) values(2, 150);
insert into place_like(member_id, place_id) values(2, 50);
insert into place_like(member_id, place_id) values(2, 253);
insert into place_like(member_id, place_id) values(2, 701);
insert into place_like(member_id, place_id) values(2, 437);
insert into place_like(member_id, place_id) values(2, 28);
insert into place_like(member_id, place_id) values(2, 485);
insert into place_like(member_id, place_id) values(2, 531);
insert into place_like(member_id, place_id) values(2, 386);
insert into place_like(member_id, place_id) values(2, 21);
insert into place_like(member_id, place_id) values(2, 616);
insert into place_like(member_id, place_id) values(2, 631);
insert into place_like(member_id, place_id) values(2, 397);
insert into place_like(member_id, place_id) values(2, 552);
insert into place_like(member_id, place_id) values(2, 137);
insert into place_like(member_id, place_id) values(2, 638);
insert into place_like(member_id, place_id) values(3, 424);
insert into place_like(member_id, place_id) values(3, 350);
insert into place_like(member_id, place_id) values(3, 131);
insert into place_like(member_id, place_id) values(3, 309);
insert into place_like(member_id, place_id) values(3, 71);
insert into place_like(member_id, place_id) values(3, 488);
insert into place_like(member_id, place_id) values(3, 342);
insert into place_like(member_id, place_id) values(3, 483);
insert into place_like(member_id, place_id) values(3, 735);
insert into place_like(member_id, place_id) values(3, 196);
insert into place_like(member_id, place_id) values(3, 575);
insert into place_like(member_id, place_id) values(3, 251);
insert into place_like(member_id, place_id) values(3, 10);
insert into place_like(member_id, place_id) values(3, 555);
insert into place_like(member_id, place_id) values(3, 443);
insert into place_like(member_id, place_id) values(3, 638);
insert into place_like(member_id, place_id) values(3, 14);
insert into place_like(member_id, place_id) values(3, 650);
insert into place_like(member_id, place_id) values(3, 363);
insert into place_like(member_id, place_id) values(3, 102);